# Generated by Django 2.1.4 on 2019-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample',
            field=models.FileField(default='', upload_to='music_previews/'),
        ),
    ]
