# Generated by Django 2.1.4 on 2019-12-09 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0004_product_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='sample',
            field=models.FileField(default='', help_text='NB: upload samples for previewing', upload_to='music_previews/'),
        ),
    ]
