# Generated by Django 2.1.4 on 2019-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0005_auto_20191209_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
