# Generated by Django 2.1.4 on 2019-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0006_auto_20191209_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
