# Generated by Django 2.1.4 on 2019-12-09 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0008_product_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
        ),
    ]
