# Generated by Django 2.1.4 on 2019-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0012_auto_20191210_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
