# Generated by Django 2.1.4 on 2019-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0017_auto_20191212_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(auto_created=True),
        ),
    ]
