# Generated by Django 2.1.4 on 2019-12-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0020_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'User-related-images'},
        ),
    ]
