# Generated by Django 2.1.4 on 2019-12-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0022_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
