# Generated by Django 2.1.4 on 2019-12-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0023_auto_20191219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
