# Generated by Django 2.1.4 on 2019-12-21 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbeats', '0024_auto_20191220_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=Decimal('1'), help_text='Enter discount in decimal format; e.g 25/100 = .25', null=True),
        ),
    ]
