# Generated by Django 2.1.4 on 2020-04-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kevibes', '0004_auto_20191228_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-release_date'], 'permissions': (('can_download_product', 'Product can be downloaded'),)},
        ),
    ]
