# Generated by Django 2.1.4 on 2020-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevibes', '0005_auto_20200423_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_cover/'),
        ),
    ]
