# Generated by Django 2.1.4 on 2020-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevibes', '0006_auto_20200424_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
