# Generated by Django 2.1.4 on 2020-11-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kevibes', '0008_auto_20201116_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase Record'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(to='kevibes.Product'),
        ),
    ]
